"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "./_components/main-layout";
import StoreProvider from "@/store/provider";
import { GloabalAlertDialogProvider } from "@/components/global-alert-dialog";
import { Toaster } from "sonner";
import GlobalLoading from "@/components/global-loading";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("Layout renderrrrrrrrrrrrrrr");

  const pathname = usePathname();
  const pathnameNotUseLayout = [
    "/login",
    "/terms-of-service",
    "/privacy-policy",
  ];

  if (pathnameNotUseLayout.includes(pathname)) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <GloabalAlertDialogProvider>
            <MainLayout>{children}</MainLayout>
          </GloabalAlertDialogProvider>
        </StoreProvider>

        <Toaster />
        <GlobalLoading />
      </body>
    </html>
  );
}
